version: '3'

services:
  mybot:
    build: .
    restart: always
    ports:
      - "8081:8081/tcp"
    volumes:
      - ./data/:/app/data
      - ./logs/:/app/logs

volumes:
  mybot_data:
  mybot_logs:

